host:
database:
username:
password:

essenceActive: false
essenceIncrease:
essenceTime:
essenceTimeRemaining:
essenceOwner:
essenceThanks:

developmentMode: false

launchersUp: []
launchersForward: []