host: 69.162.95.98:3306
database: brethenn40012DB
username: brethenn40012
password: qNdP61mDfV9c

essenceActive: false
essenceIncrease:
essenceTime:
essenceTimeRemaining:
essenceOwner:
essenceThanks:

developmentMode: false