main: me.gamerbah.Battlegrounds
name: Battlegrounds
author: GamerBah
version: 0.2.1a
commands:
  rank:
    description: Changes a players rank
  clearchat:
    description: Clears the chat
    aliases: [cc, cchat]
  lockchat:
    description: Locks the chat and allows only Staff members to talk
    aliases: [lc, lchat]
  cmdspy:
    description: Allows Staff members to see all executed commands
  staff:
    description: Chat in the Staff channel
    aliases: [s]
  freeze:
    description: Freezes players
  mute:
    description: Mutes a player
  unmute:
    description: Unmutes a player
  flyspeed:
    description: Sets your flying speed
    aliases: [fspeed, fsp]
  report:
    description: Report a player
  staffreq:
    description: Requests a Staff member
  team:
    description: Team with another player!
  spawn:
    description: Takes you back to the spawn
  afk:
    description: Sets you as AFK (away-from-keyboard)
  message:
    description: Message another player
    aliases: [m, msg]
  reply:
    description: Quick reply to your last-received message
    aliases: [r]
  options:
    description: Open options for a player
  ping:
    description: View the ping of yourself or another player
  essence:
    description:
  essences:
    description: View your Battle Essences
  thanks:
    description: Thanks a player for activating an Essence